### ISSUE TITLE
Should the Mandrill adapter use one of the API client available on Hex

### ISSUE THREAD

**Issue by stevedomin** [paulcsmith/bamboo#58]
It feels like it would be nicer if the adapters were not coupled to the bamboo codebase.

What do you think?

**Comment by stevedomin** [comment]
I meant the underlying "driver" for the adapter. That way bamboo benefits from the latest improvements in the API and their client libraries (less maintenance work for you).

**Comment by paulcsmith** [comment]
@stevedomin I thought about doing that, but decided against it for a couple of reasons

* If you want to update just the Mandrill dependency in your app, but Bamboo hasn't been updated, you could have conflicts and have to override the mandrill version, which *might* cause issues. Or if you update Bamboo and it requires a new version of Mandrill, you may not want to update the rest of your app to use the new version of the Mandrill package.
* The actual implementation for sending emails is pretty small: https://github.com/paulcsmith/bamboo/blob/master/lib/bamboo/adapters/mandrill_adapter.ex#L6-L34 Most of those lines are for the error message.
* The Mandrill package includes a ton of extra functions that Bamboo doesn't really use or need.

So in the end, I don't think maintaining it in Bamboo will be hard, and will likely be better for end users since they won't have to worry about Mandrill version mismatches.

What do you think?

**Comment by paulcsmith** [comment]
Chatted on Slack. I may move adapters out of Bamboo core, but for now I'll keep them here for simplicity
